//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFridgeListWebapi.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFridgeListWebapi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dein Passwort wurde erfolgreich geändert! ähnelt.
        /// </summary>
        public static string ChangePasswordSucceededMailHeaderText {
            get {
                return ResourceManager.GetString("ChangePasswordSucceededMailHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast dein Passwort geändert ähnelt.
        /// </summary>
        public static string ChangePasswordSucceededMailSubject {
            get {
                return ResourceManager.GetString("ChangePasswordSucceededMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bad Request. ähnelt.
        /// </summary>
        public static string ErrorHttp400 {
            get {
                return ResourceManager.GetString("ErrorHttp400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unauthorized. ähnelt.
        /// </summary>
        public static string ErrorHttp401 {
            get {
                return ResourceManager.GetString("ErrorHttp401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forbidden. ähnelt.
        /// </summary>
        public static string ErrorHttp403 {
            get {
                return ResourceManager.GetString("ErrorHttp403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Found. ähnelt.
        /// </summary>
        public static string ErrorHttp404 {
            get {
                return ResourceManager.GetString("ErrorHttp404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method Not Allowed ähnelt.
        /// </summary>
        public static string ErrorHttp405 {
            get {
                return ResourceManager.GetString("ErrorHttp405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Server Error. ähnelt.
        /// </summary>
        public static string ErrorHttp500 {
            get {
                return ResourceManager.GetString("ErrorHttp500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das ändern des Passworts war nicht erfolgreich. ähnelt.
        /// </summary>
        public static string IdentityErrorChangePasswordFails {
            get {
                return ResourceManager.GetString("IdentityErrorChangePasswordFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bzgl. der Optimistischen Nebenläufigkeit, das Objekt wurde verändert. ähnelt.
        /// </summary>
        public static string IdentityErrorConcurrencyFailure {
            get {
                return ResourceManager.GetString("IdentityErrorConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein unbekannter Fehler ist aufgetreten. ähnelt.
        /// </summary>
        public static string IdentityErrorDefaultError {
            get {
                return ResourceManager.GetString("IdentityErrorDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail &apos;{0}&apos; ist bereits vergeben. ähnelt.
        /// </summary>
        public static string IdentityErrorDuplicateEmail {
            get {
                return ResourceManager.GetString("IdentityErrorDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rollen-Name &apos;{0}&apos; ist bereits vergeben. ähnelt.
        /// </summary>
        public static string IdentityErrorDuplicateRoleName {
            get {
                return ResourceManager.GetString("IdentityErrorDuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername &apos;{0}&apos; ist bereits vergeben. ähnelt.
        /// </summary>
        public static string IdentityErrorDuplicateUserName {
            get {
                return ResourceManager.GetString("IdentityErrorDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail &apos;{0}&apos; ist ungültig. ähnelt.
        /// </summary>
        public static string IdentityErrorInvalidEmail {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rollen-Name &apos;{0}&apos; ist ungültig. ähnelt.
        /// </summary>
        public static string IdentityErrorInvalidRoleName {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiger Token. ähnelt.
        /// </summary>
        public static string IdentityErrorInvalidToken {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername &apos;{0}&apos; ist ungültig. Erlaubt sind nur Buchstaben und Zahlen. ähnelt.
        /// </summary>
        public static string IdentityErrorInvalidUserName {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist bereits ein Nutzer mit diesem Login vorhanden. ähnelt.
        /// </summary>
        public static string IdentityErrorLoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("IdentityErrorLoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiges Passwort. ähnelt.
        /// </summary>
        public static string IdentityErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort muss mindestens eine Ziffer enthalten (&apos;0&apos;-&apos;9&apos;). ähnelt.
        /// </summary>
        public static string IdentityErrorPasswordRequiresDigit {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort muss mindestens einen Kleinbuchstaben enthalten (&apos;a&apos;-&apos;z&apos;). ähnelt.
        /// </summary>
        public static string IdentityErrorPasswordRequiresLower {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort muss mindestens ein Sonderzeichen enthalten. ähnelt.
        /// </summary>
        public static string IdentityErrorPasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort muss mindestens einen Großbuchstaben enthalten (&apos;A&apos;-&apos;Z&apos;). ähnelt.
        /// </summary>
        public static string IdentityErrorPasswordRequiresUpper {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort muss mindestens {0} Zeichen lang sein. ähnelt.
        /// </summary>
        public static string IdentityErrorPasswordTooShort {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Bestätigung ihres Accounts ist fehlgeschlagen. ähnelt.
        /// </summary>
        public static string IdentityErrorSignUpConfirmFails {
            get {
                return ResourceManager.GetString("IdentityErrorSignUpConfirmFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer hat bereits ein Passwort gesetzt. ähnelt.
        /// </summary>
        public static string IdentityErrorUserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("IdentityErrorUserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer ist bereits in Rolle &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string IdentityErrorUserAlreadyInRole {
            get {
                return ResourceManager.GetString("IdentityErrorUserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aussperrung ist für diesen Benutzer nicht aktiviert. ähnelt.
        /// </summary>
        public static string IdentityErrorUserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("IdentityErrorUserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer ist nicht in Rolle &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string IdentityErrorUserNotInRole {
            get {
                return ResourceManager.GetString("IdentityErrorUserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur noch ein Klick! ähnelt.
        /// </summary>
        public static string RegistrationEmailHeader {
            get {
                return ResourceManager.GetString("RegistrationEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Registrierung auf Seracom ähnelt.
        /// </summary>
        public static string RegistrationMailSubject {
            get {
                return ResourceManager.GetString("RegistrationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast Dein Passwort vergessen? ähnelt.
        /// </summary>
        public static string ResetPasswordMailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort wurde erfolgreich zurückgesetzt. Du erhälst in Kürze eine E-Mail mit der du ein neues Passwort vergeben kannst. ähnelt.
        /// </summary>
        public static string ResetPasswordRequestSucceeded {
            get {
                return ResourceManager.GetString("ResetPasswordRequestSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dein Passwort wurde erfolgreich zurückgesetzt! ähnelt.
        /// </summary>
        public static string ResetPasswordSucceededMailHeaderText {
            get {
                return ResourceManager.GetString("ResetPasswordSucceededMailHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwortänderung erfolgreich ähnelt.
        /// </summary>
        public static string ResetPasswordSucceededMailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSucceededMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwortänderung erfolgreich. ähnelt.
        /// </summary>
        public static string ResetPasswordSucceededSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSucceededSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Artikel mit der ID {0} existiert nicht. ähnelt.
        /// </summary>
        public static string ValidationErrorArticleWithIdNotExists {
            get {
                return ResourceManager.GetString("ValidationErrorArticleWithIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Kühlschrank mit der ID {0} existiert nicht. ähnelt.
        /// </summary>
        public static string ValidationErrorFridgeWithIdNotExists {
            get {
                return ResourceManager.GetString("ValidationErrorFridgeWithIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Kühlschrank mit dem Name {0} existiert bereits. ähnelt.
        /// </summary>
        public static string ValidationErrorFridgeWithNameStillExists {
            get {
                return ResourceManager.GetString("ValidationErrorFridgeWithNameStillExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die übergebene E-Mail Adresse ist ungültig. ähnelt.
        /// </summary>
        public static string ValidationErrorInvalidEmailAddress {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Artikel mit der ID {0} existiert nicht. ähnelt.
        /// </summary>
        public static string ValidationErrorItemWithIdNotExists {
            get {
                return ResourceManager.GetString("ValidationErrorItemWithIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie die Menge ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingArticleAmount {
            get {
                return ResourceManager.GetString("ValidationErrorMissingArticleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie ein Mindesthaltbarkeitsdatum an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingArticleExpiryDate {
            get {
                return ResourceManager.GetString("ValidationErrorMissingArticleExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie die ID des Article ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingArticleId {
            get {
                return ResourceManager.GetString("ValidationErrorMissingArticleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie ein Label an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingArticleLabel {
            get {
                return ResourceManager.GetString("ValidationErrorMissingArticleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie einen Bestätigungscode an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingConfirmCode {
            get {
                return ResourceManager.GetString("ValidationErrorMissingConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie das aktuelle Passwort an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingCurrentPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMissingCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie eine E-Mail Adresse an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingEmailAddress {
            get {
                return ResourceManager.GetString("ValidationErrorMissingEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie die ID des Kühlschranks ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingFridgeId {
            get {
                return ResourceManager.GetString("ValidationErrorMissingFridgeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie den Namen des Kühlschranks ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingFridgeName {
            get {
                return ResourceManager.GetString("ValidationErrorMissingFridgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie die ID des Article ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingItemId {
            get {
                return ResourceManager.GetString("ValidationErrorMissingItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie den Namen des Artikel ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingItemName {
            get {
                return ResourceManager.GetString("ValidationErrorMissingItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie ein das neues Passwort an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingNewPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMissingNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie ein Passwort an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie die ID der Einkaufsliste ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingShoppinglistId {
            get {
                return ResourceManager.GetString("ValidationErrorMissingShoppinglistId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie den Namen der Einkaufsliste ein. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingShoppinglistName {
            get {
                return ResourceManager.GetString("ValidationErrorMissingShoppinglistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie eine Benuzer Id an. ähnelt.
        /// </summary>
        public static string ValidationErrorMissingUserId {
            get {
                return ResourceManager.GetString("ValidationErrorMissingUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr neues Passwort darf nicht identisch zu dem aktuellen sein. ähnelt.
        /// </summary>
        public static string ValidationErrorNewPasswordEqualsCurrentPassword {
            get {
                return ResourceManager.GetString("ValidationErrorNewPasswordEqualsCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort muss mindestens 8 Zeichen lang sein. ähnelt.
        /// </summary>
        public static string ValidationErrorPasswordLessEightCharacter {
            get {
                return ResourceManager.GetString("ValidationErrorPasswordLessEightCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Einkaufsliste mit der ID {0} existiert nicht. ähnelt.
        /// </summary>
        public static string ValidationErrorShoppinglistWithIdNotExists {
            get {
                return ResourceManager.GetString("ValidationErrorShoppinglistWithIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Einkaufsliste mit dem Name {0} existiert bereits. ähnelt.
        /// </summary>
        public static string ValidationErrorShoppinglistWithNameStillExists {
            get {
                return ResourceManager.GetString("ValidationErrorShoppinglistWithNameStillExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Benutzer ist nicht berechtigt die gewünschte Aktion durchzuführen. ähnelt.
        /// </summary>
        public static string ValidationErrorUserIsNotAllowed {
            get {
                return ResourceManager.GetString("ValidationErrorUserIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Benutzer ist ausgeloggt. ähnelt.
        /// </summary>
        public static string ValidationErrorUserLockedOut {
            get {
                return ResourceManager.GetString("ValidationErrorUserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte kein Benutzer mit der E-Mail-Adresse {0} gefunden werden. ähnelt.
        /// </summary>
        public static string ValidationErrorUserNotFoundByEmail {
            get {
                return ResourceManager.GetString("ValidationErrorUserNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte kein Benutzer mit der ID {0} gefunden werden. ähnelt.
        /// </summary>
        public static string ValidationErrorUserNotFoundById {
            get {
                return ResourceManager.GetString("ValidationErrorUserNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Benutzerkonto wurde noch nicht bestätigt.
        ///Bitte bestätige dein Konto über die E-Mail, die du erhalten hast und melde dich erneut an. ähnelt.
        /// </summary>
        public static string ValidationErrorUserSignUpNotConfirmed {
            get {
                return ResourceManager.GetString("ValidationErrorUserSignUpNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das eingegebene Passwort ist ungültig. ähnelt.
        /// </summary>
        public static string ValidationErrorWrongPassword {
            get {
                return ResourceManager.GetString("ValidationErrorWrongPassword", resourceCulture);
            }
        }
    }
}
