//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFridgeListWebapi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFridgeListWebapi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort wurde erfolgreich geändert!.
        /// </summary>
        public static string ChangePasswordSucceededMailHeaderText {
            get {
                return ResourceManager.GetString("ChangePasswordSucceededMailHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast dein Passwort geändert.
        /// </summary>
        public static string ChangePasswordSucceededMailSubject {
            get {
                return ResourceManager.GetString("ChangePasswordSucceededMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request..
        /// </summary>
        public static string ErrorHttp400 {
            get {
                return ResourceManager.GetString("ErrorHttp400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string ErrorHttp401 {
            get {
                return ResourceManager.GetString("ErrorHttp401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden..
        /// </summary>
        public static string ErrorHttp403 {
            get {
                return ResourceManager.GetString("ErrorHttp403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found..
        /// </summary>
        public static string ErrorHttp404 {
            get {
                return ResourceManager.GetString("ErrorHttp404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Not Allowed.
        /// </summary>
        public static string ErrorHttp405 {
            get {
                return ResourceManager.GetString("ErrorHttp405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        public static string ErrorHttp500 {
            get {
                return ResourceManager.GetString("ErrorHttp500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ändern des Passworts war nicht erfolgreich..
        /// </summary>
        public static string IdentityErrorChangePasswordFails {
            get {
                return ResourceManager.GetString("IdentityErrorChangePasswordFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bzgl. der Optimistischen Nebenläufigkeit, das Objekt wurde verändert..
        /// </summary>
        public static string IdentityErrorConcurrencyFailure {
            get {
                return ResourceManager.GetString("IdentityErrorConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unbekannter Fehler ist aufgetreten..
        /// </summary>
        public static string IdentityErrorDefaultError {
            get {
                return ResourceManager.GetString("IdentityErrorDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail &apos;{0}&apos; ist bereits vergeben..
        /// </summary>
        public static string IdentityErrorDuplicateEmail {
            get {
                return ResourceManager.GetString("IdentityErrorDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollen-Name &apos;{0}&apos; ist bereits vergeben..
        /// </summary>
        public static string IdentityErrorDuplicateRoleName {
            get {
                return ResourceManager.GetString("IdentityErrorDuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername &apos;{0}&apos; ist bereits vergeben..
        /// </summary>
        public static string IdentityErrorDuplicateUserName {
            get {
                return ResourceManager.GetString("IdentityErrorDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail &apos;{0}&apos; ist ungültig..
        /// </summary>
        public static string IdentityErrorInvalidEmail {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollen-Name &apos;{0}&apos; ist ungültig..
        /// </summary>
        public static string IdentityErrorInvalidRoleName {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Token..
        /// </summary>
        public static string IdentityErrorInvalidToken {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername &apos;{0}&apos; ist ungültig. Erlaubt sind nur Buchstaben und Zahlen..
        /// </summary>
        public static string IdentityErrorInvalidUserName {
            get {
                return ResourceManager.GetString("IdentityErrorInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist bereits ein Nutzer mit diesem Login vorhanden..
        /// </summary>
        public static string IdentityErrorLoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("IdentityErrorLoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Passwort..
        /// </summary>
        public static string IdentityErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort muss mindestens eine Ziffer enthalten (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string IdentityErrorPasswordRequiresDigit {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort muss mindestens einen Kleinbuchstaben enthalten (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string IdentityErrorPasswordRequiresLower {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort muss mindestens ein Sonderzeichen enthalten..
        /// </summary>
        public static string IdentityErrorPasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort muss mindestens einen Großbuchstaben enthalten (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string IdentityErrorPasswordRequiresUpper {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort muss mindestens {0} Zeichen lang sein..
        /// </summary>
        public static string IdentityErrorPasswordTooShort {
            get {
                return ResourceManager.GetString("IdentityErrorPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Bestätigung ihres Accounts ist fehlgeschlagen..
        /// </summary>
        public static string IdentityErrorSignUpConfirmFails {
            get {
                return ResourceManager.GetString("IdentityErrorSignUpConfirmFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer hat bereits ein Passwort gesetzt..
        /// </summary>
        public static string IdentityErrorUserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("IdentityErrorUserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ist bereits in Rolle &apos;{0}&apos;..
        /// </summary>
        public static string IdentityErrorUserAlreadyInRole {
            get {
                return ResourceManager.GetString("IdentityErrorUserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aussperrung ist für diesen Benutzer nicht aktiviert..
        /// </summary>
        public static string IdentityErrorUserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("IdentityErrorUserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ist nicht in Rolle &apos;{0}&apos;..
        /// </summary>
        public static string IdentityErrorUserNotInRole {
            get {
                return ResourceManager.GetString("IdentityErrorUserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur noch ein Klick!.
        /// </summary>
        public static string RegistrationEmailHeader {
            get {
                return ResourceManager.GetString("RegistrationEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Registrierung auf Seracom.
        /// </summary>
        public static string RegistrationMailSubject {
            get {
                return ResourceManager.GetString("RegistrationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast Dein Passwort vergessen?.
        /// </summary>
        public static string ResetPasswordMailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort wurde erfolgreich zurückgesetzt. Du erhälst in Kürze eine E-Mail mit der du ein neues Passwort vergeben kannst..
        /// </summary>
        public static string ResetPasswordRequestSucceeded {
            get {
                return ResourceManager.GetString("ResetPasswordRequestSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort wurde erfolgreich zurückgesetzt!.
        /// </summary>
        public static string ResetPasswordSucceededMailHeaderText {
            get {
                return ResourceManager.GetString("ResetPasswordSucceededMailHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwortänderung erfolgreich.
        /// </summary>
        public static string ResetPasswordSucceededMailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSucceededMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwortänderung erfolgreich..
        /// </summary>
        public static string ResetPasswordSucceededSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSucceededSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die übergebene E-Mail Adresse ist ungültig..
        /// </summary>
        public static string ValidationErrorInvalidEmailAddress {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie einen Bestätigungscode an..
        /// </summary>
        public static string ValidationErrorMissingConfirmCode {
            get {
                return ResourceManager.GetString("ValidationErrorMissingConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie das aktuelle Passwort an..
        /// </summary>
        public static string ValidationErrorMissingCurrentPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMissingCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie eine E-Mail Adresse an..
        /// </summary>
        public static string ValidationErrorMissingEmailAddress {
            get {
                return ResourceManager.GetString("ValidationErrorMissingEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie ein das neues Passwort an..
        /// </summary>
        public static string ValidationErrorMissingNewPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMissingNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie ein Passwort an..
        /// </summary>
        public static string ValidationErrorMissingPassword {
            get {
                return ResourceManager.GetString("ValidationErrorMissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie eine Benuzer Id an..
        /// </summary>
        public static string ValidationErrorMissingUserId {
            get {
                return ResourceManager.GetString("ValidationErrorMissingUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr neues Passwort darf nicht identisch zu dem aktuellen sein..
        /// </summary>
        public static string ValidationErrorNewPasswordEqualsCurrentPassword {
            get {
                return ResourceManager.GetString("ValidationErrorNewPasswordEqualsCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens 8 Zeichen lang sein..
        /// </summary>
        public static string ValidationErrorPasswordLessEightCharacter {
            get {
                return ResourceManager.GetString("ValidationErrorPasswordLessEightCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer ist nicht berechtigt die gewünschte Aktion durchzuführen..
        /// </summary>
        public static string ValidationErrorUserIsNotAllowed {
            get {
                return ResourceManager.GetString("ValidationErrorUserIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer ist ausgeloggt..
        /// </summary>
        public static string ValidationErrorUserLockedOut {
            get {
                return ResourceManager.GetString("ValidationErrorUserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte kein Benutzer mit der E-Mail-Adresse {0} gefunden werden..
        /// </summary>
        public static string ValidationErrorUserNotFoundByEmail {
            get {
                return ResourceManager.GetString("ValidationErrorUserNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte kein Benutzer mit der ID {0} gefunden werden..
        /// </summary>
        public static string ValidationErrorUserNotFoundById {
            get {
                return ResourceManager.GetString("ValidationErrorUserNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Benutzerkonto wurde noch nicht bestätigt.
        ///Bitte bestätige dein Konto über die E-Mail, die du erhalten hast und melde dich erneut an..
        /// </summary>
        public static string ValidationErrorUserSignUpNotConfirmed {
            get {
                return ResourceManager.GetString("ValidationErrorUserSignUpNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das eingegebene Passwort ist ungültig..
        /// </summary>
        public static string ValidationErrorWrongPassword {
            get {
                return ResourceManager.GetString("ValidationErrorWrongPassword", resourceCulture);
            }
        }
    }
}
